version: '3.8'

services:
  bedrock-access-gateway:
    build:
      context: ./src
      dockerfile: Dockerfile_ecs
    ports:
      - "127.0.0.1:8000:8080"
    env_file:
      - ./.env
    volumes:
      - ${HOME}/.aws:/home/appuser/.aws
